import { Console } from 'console'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  /**
 * @function
 * @param {number};
 * @returns {x} The value of x, People, Power or People Power
 */
  const divsibleNumbersThreeAndFive = (N:Number) => {
    try {
        for (var x =0; x<= N; x++){
            var step = 0;
            if (x % 3 == 0) {
                console.log ("People")
                step = 1;
            }
            if (x % 5 == 0) {
                console.log ("Power")
                step = 1;
            }
            if (!step) {
              console.log ({x})
            }
          }  
      } catch (error) {
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Type script program to print numbers from 1 to 100
        </h1>
      </main>
        {/* Function Call, it accepts type of Number */}
        {divsibleNumbersThreeAndFive(100)}
    </div>
  )
}

export default Home
